var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "          y   y                                                  o              ",
   "         y y y y                                                xxx             ",
   "        y   y   y                                                               ",
   "        y       y         x                                   x     x           ",
   "         y     y         xxx           o                      x!!!!!x           ",
   "          y   y         xx!xx         xxx                 0   xx!!!xx           ",
   "           y y      o    xxx                         o   xxx   xxxxx            ",
   "            y             x                     0   xxx          x          xx  ",
   "  xx                                           xxx               xx          x  ",
   "  x            o          0                o                     x           x  ",
   "  x                       x               xxx                    x         o x  ",
   "  x           xxxx       xxx      xx                                         x  ",
   "  x  @                  xx!xx                 0     0                        x  ",
   "  xxxxxxxxxx        xxxxxxxxxxxxx    xxxx    xxx   xxx     xxxxxxxxxxxxxxxxxxx  ",
   "           x        x           x    x  x                  x                    ",
   "           x!!!!!!!!x           x!!!!x  x!!!!!!!!!!!!!!!!!!x                    ",
   "           x!!!!!!!!x           x!!!!x  x!!!!!!!!!!!!!!!!!!x                    ",
   "           xxxxxxxxxx           xxxxxx  xxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                      xxx                                                             xxx                         ",
   "                      x!x                                                             x!x                         ",
   "                      x!x                                                             x!x                         ",
   "                      xvx                                                             xvx                         ",
   "                                              xxxxxxx                                                             ",
   "                                                  |x|                    o                   xxx                  ",
   "                                                   x                    xxx                  x x                  ",
   "                                       o           x                    x!x                  x                    ",
   "                                       xx          x   xx               x!x      xx          x                    ",
   "                                                   x                    xvx      x          xx                    ",
   "                       o                     xx    x       o                     x           x                    ",
   "                      xxx                o        ox       xx                    x o         x                    ",
   "                xxx    v                 xx       xx                             xxx         x                    ",
   "          xxx               xxx                    x    xx                       x          ox                    ",
   "     @                                             x                             x         xxx                    ",
   "    xxx                                           oxo                            xo          x                    ",
   "                                      xx  xxx   xxxxxxx    xxxxxx                xxxx        x                    ",
   "!!!!!!!!xx             o             x!!!!!!!!!!!!!!!!!!!!!!!!!!!x               x         o x                    ",
   "!!!!!!!!!!x       o        o        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                       xxxx                    ",
   "!!!!!!!!!!!x     xxx      xxx      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                         x                    ",
   "!!!!!!!!!!!!x                     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                        x                    ",
   "!!!!!!!!!!!!!x         o         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     o     k        o  x                    ",
   "!!!!!!!!!!!!!!xxx   xxxxxx   xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  xxx   xxxxx   xxxxxx                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                         "],
   ["                                                                                                                  ",
    "                                                                                                                  ",
    "                                               o                                                                  ",
    "                                              xxx                                                                 ",
    "                                                                                                                  ",
    "                                            x     x                                    xxxxxxxxxxxxxx             ",
    "                                            x!!!!!x  x                                 xx!!!xxxx!!!xx             ",
    "                                            xx!!!xx                                    x  v      v  x             ",
    "                                             xxxxx                        x            x            x             ",
    "                                               x        o                 x            x            x             ",
    "                      x                        xx       x                xx            xx           x             ",
    "                     xxx                       x                          x            x      x     x             ",
    "                    xxxxx                      x    x                   xxxxx          x     xx     x             ",
    "                   xx!!!xx                                             xx!!!xx         x      x     x             ",
    "                  xx!!!!!xx                    o                       x!!!!!x         x      x    xx             ",
    "                  x   v   x              xx=          xx               xv v vx         xx     x     x             ",
    "                  x   o   x            xx               xx                             x      x     x             ",
    "                  x      xx          xx                   xx                           x      xx    x             ",
    "                                                                                       x     xx     x             ",
    "                                                                                       x      x    xx             ",
    "           o         x                                                                 xx     x     x             ",
    "                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      x      x     x             ",
    "     @            o    o    o     xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                            xx    x             ",
    "xxxxxxxxxx   x    x    x    x    xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx                          xx     x             ",
    "         x!!!x                  xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                          x     x             ",
    "         x!!!xx                                                                               x  o  x             ",
    "         x!!!x                   k                                              xxxxxxxx      xxxxxxx             ",
    "         x!!!x                   xx   o        o        o                       x          o        x             ",
    "         x!!!xxxx            xxxxxxx xx xx xx xx xx xx xx xx xx xxxxxxx        xx        xxxx       x             ",
    "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  x!!!!!!!x             "],
   ["                                                                                    ",
    "                                                                                    ",
    "          x    x                       xx       xx                                  ",
    "          x    x    @                  xx       xx  xx                y   y         ",
    "          xx  xx   xxx   xx  xx        xx       xx  xx               y y y y        ",
    "           xxxx   xxxxx  xx  xx        xx       xx      xx          y   y   y       ",
    "            xx   xx   xx xx  xx        xx       xx  xx  xxxxxx      y       y       ",
    "            xx   xx   xx xx  xx        xx   x   xx  xx  xxxxxx       y     y        ",
    "            xx   xx   xx xx  xx        xxx xxx xxx  xx  xx  xx        y   y         ",
    "            xx    xxxxx  xxxxxx        xxxxxxxxxxx  xx  xx  xx         y y          ",
    "            xx     xxx    xxxx          xxx   xxx   xx  xx  xx          y           ",
    "                                                                                    ",
    "                                   k                         k                      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
